name: GraphQL Python Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12' ]
    name: Python ${{ matrix.python-version }} sample

    services:
      graphql:
        build: ./Github-test/
        ports:
          - 4000:4000
        options: --health-cmd="curl -f http://localhost:4000/ || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }} 
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for GraphQL server
        run: |
          until curl -s http://localhost:4000/health; do
            echo "Waiting for GraphQL server..."
            sleep 5
          done

      - name: Run GraphQL-cop normal test
        run: python graphql-cop.py -t http://localhost:4000/

      - name: Run GraphQL-cop force test
        run: python graphql-cop.py -t http://localhost:4000/ -f

      - name: Run GraphQL-cop normal test with html output
        run: python graphql-cop.py -t http://localhost:4000/ -f -o html
